services:
  analytics-server:
    build:
      context: ./apps/analytics-server
    ports:
      - 8000:8000
  
  postgres:
    image: postgres:17.0
    container_name: polar_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polar_edge
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
