services:
  postgres:
    image: postgres:17.0
    container_name: polar_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polar_edge
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

volumes:
  postgres-data:
