# https://docs.docker.com/go/compose-spec-reference/

services:
  next-app:
    container_name: next
    build:
      context: next
      dockerfile: Dockerfile
    env_file:
      - .env.local
    restart: always
    ports:
      - 3000:3000
    networks:
      - server

networks:
  server:
