packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - sharp
catalog:
  vitest: ^4.0.17
  "@vitest/coverage-istanbul": ^4.0.17
  unplugin-swc: ^1.5.0
  typescript: ^5.9.3
  "@types/node": ^24.10.9
  zod: ^4.3.5
  next: 16.1.1
  react: 19.2.3
  react-dom: 19.2.3
  "@types/react": ^19.2.8
  "@types/react-dom": ^19.2.3
overrides:
  esbuild: ^0.25.0
