packages:
  - apps/*
  - packages/*

catalog:
  "@types/node": ^24.10.9
  "@types/react": ^19.2.8
  "@types/react-dom": ^19.2.3
  "@vitest/coverage-istanbul": ^4.0.17
  ai: 6.0.39
  next: 16.1.5
  react: 19.2.3
  react-dom: 19.2.3
  tsdown: 0.19.0
  typescript: ^5.9.3
  unplugin-swc: ^1.5.0
  vitest: ^4.0.17
  zod: ^4.3.5

onlyBuiltDependencies:
  - sharp

overrides:
  esbuild: ^0.25.0
