import type { Metadata } from "next";
import "@repo/ui/styles/globals.css";
import { Libre_Franklin } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  variable: "--font-libre-franklin",
});

export default function RootLayout(props: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={`${libreFranklin.variable} font-sans antialiased`}>
        {props.unauth}
        {props.auth}
      </body>
    </html>
  );
}
