name: Setup Site
description: Actions to perform in order to test the site
on: workflow_call
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
          node-version: 22.11.0
    - name: Install dependencies
      run: npm ci
      shell: bash
