name: Interaction and Accessibility Tests
description: Run Storybook's interaction and accessibility test suite
on: workflow_call
runs:
  using: composite
  steps:
    - uses: ./.github/actions/site-setup
    - name: Build Storybook
      run: npm run build:storybook --quiet;
    - name: Serve Storybook and run tests
      run: |
            npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
