name: Build Next.js
on: workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node/node_modules
        uses: ./.github/actions/site-setup

      - name: Run Next.js Build
        run: turbo build --filter=web
        shell: bash
