name: Build Next.js
on: workflow_call
jobs:
    build:
        runs-on: ubuntu-latest
        environment: ci
        env:
            POSTGRES_URL: ${{ vars.POSTGRES_URL }}
            NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_REDIRECT_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_REDIRECT_URL }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node/node_modules
              uses: ./.github/actions/site-setup

            - name: echo some things
              run: echo ${{ vars.POSTGRES_URL }}

            - name: Run tests
              run: npm run build
              shell: bash
