name: Build Next.js
on: workflow_call
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node/node_modules
              uses: ./.github/actions/site-setup

            - name: Run tests
              run: npm run build
              shell: bash
