name: Build Next.js
on: workflow_call
jobs:
    build:
        runs-on: ubuntu-latest
        environment: ci
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node/node_modules
              uses: ./.github/actions/site-setup

            - name: Run tests
              run: npm run build
              shell: bash
              env:
                  POSTGRES_URL: ${{ vars.POSTGRES_URL }}
                  NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
                  NEXT_PUBLIC_SUPABASE_REDIRECT_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_REDIRECT_URL }}
                  SUPABASE_AUTH_DISCORD_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_DISCORD_CLIENT_ID }}
                  SUPABASE_AUTH_DISCORD_SECRET: ${{ secrets.SUPABASE_AUTH_DISCORD_SECRET }}
                  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
                  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
