on:
  push:
    branches:
      - "init-turbo" # change to the branch you wish to deploy from
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: false
          install_command: cd storybook && npm install
          path: storybook/storybook-static # change to your build folder
          build_command: npm run build:storybook
