# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./next
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4

      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      # Set the working directory and install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./next

      # Build Storybook
      - name: Build Storybook
        run: npm run build-storybook
        working-directory: ./next

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: ./next/storybook-static # default: dist/storybook
          checkout: false # default: true
