name: Storybook Tests
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.0-jammy
    defaults:
      run:
        working-directory: next
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node/node_modules
        uses: ./.github/actions/site-setup

      - name: Build Storybook
        run: npm run build:storybook --quiet;
        shell: bash

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:6006 && yarn test-storybook"
        shell: bash
