name: "Interaction and Accessibility Tests"
on: push
jobs:
    # Run interaction and accessibility tests
    interaction-and-accessibility:
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.45.0-jammy
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Build Storybook
              run: npm run build:storybook --quiet;
            - name: Serve Storybook and run tests
              run: |
                  npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                    "npx http-server storybook-static --port 6006 --silent" \
                    "npx wait-on tcp:6006 && yarn test-storybook"
