name: Unit Tests
on: workflow_call
jobs:
    test:
        runs-on: ubuntu-latest
        environment: ci
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node/node_modules
              uses: ./.github/actions/site-setup

            - name: Run tests
              run: npm test
              shell: bash
